client_config_backend: settings
client_config:
  client_id: 968825057854-kj0qo17r63omr059l9vb1f53fm5u4ies.apps.googleusercontent.com
  client_secret: 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
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentails.json
get_refresh_token: True
oauth_scope: 
- https://www.googleapis.com/auth/drive